CREATE TABLE "CATEGORY" (
  "CATEGORYID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CATEGORYNAME" VARCHAR(20) NOT NULL,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CATEGORYID")
);

CREATE TABLE "CUSTOMER" (
  "CUSTOMERID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 101, INCREMENT BY 1),
  "CUSTOMERNAME" VARCHAR(30),
  "FIRSTNAME" VARCHAR(20),
  "LASTNAME" VARCHAR(30),
  "EMAIL" VARCHAR(50) NOT NULL,
  "PASSWORD" VARCHAR(70) NOT NULL,
  "PHONENUMBER" VARCHAR(20),
  "ADDRESS" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CUSTOMERID")
);

CREATE TABLE "ORDERS" (
  "ORDERID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 101, INCREMENT BY 1),
  "CUSTOMERID" INT NOT NULL,
  "PAYMENTID" INT NOT NULL,
  "PROMOTIONVALUE" DOUBLE,
  "SUBTOTAL" DOUBLE,
  "TOTAL" DOUBLE,
  "PHONENUMBER" VARCHAR(20),
  "ADDRESS" LONG VARCHAR,
  "STATUS" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ORDERID"),
    FOREIGN KEY ("CUSTOMERID")
      REFERENCES "CUSTOMER"("CUSTOMERID")
);

CREATE TABLE "PROMOTION" (
  "PROMOTIONID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "VALUE" INTEGER,
  "DESCRIPTION" LONG VARCHAR,
  "STATUS" VARCHAR(10),
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PROMOTIONID")
);

CREATE TABLE "PRODUCT" (
  "PRODUCTCODE" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 2001, INCREMENT BY 1),
  "PRODUCTNAME" VARCHAR(40),
  "DESCRIPTION" LONG VARCHAR,
  "PRICE" DOUBLE,
  "STOCK" INTEGER,
  "IMAGE" LONG VARCHAR,
  "PROMOTIONID" INT,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PRODUCTCODE"),
    FOREIGN KEY ("PROMOTIONID")
      REFERENCES "PROMOTION"("PROMOTIONID")
);

CREATE TABLE "ORDERLIST" (
  "ORDERLIST" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 201, INCREMENT BY 1), 
  "ORDERID" INT NOT NULL,
  "PRODUCTCODE" INT NOT NULL,
  "QUANTITY" INTEGER,
  PRIMARY KEY (ORDERLIST),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("ORDERID")
      REFERENCES "ORDERS"("ORDERID")
);

CREATE TABLE "STAFF" (
  "STAFFID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 201, INCREMENT BY 1),
  "STAFFNAME" VARCHAR(30),
  "PASSWORD" VARCHAR(70) NOT NULL,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("STAFFID")
);

CREATE TABLE "PAYMENT" (
  "PAYMENTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "TRANSACTIONID" VARCHAR(15),
  "METHOD" VARCHAR(25),
  "TOTAL" DOUBLE,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PAYMENTID")
);

CREATE TABLE "CART" (
  "CARTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CUSTOMERID" INT NOT NULL,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CARTID")
);

CREATE TABLE "CARTLIST" (
  "CARTLISTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CARTID" INT NOT NULL,
  "PRODUCTCODE" INT NOT NULL,
  "QUANTITY" INTEGER,
  PRIMARY KEY ("CARTLISTID"),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("CARTID")
      REFERENCES "CART"("CARTID")
);

CREATE TABLE "REFUND" (
  "REFUNDID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "PAYMENTID" INT NOT NULL,
  "STAFFID" INT NOT NULL,
  "STATUS" VARCHAR(10),
  "REASON" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("REFUNDID"),
    FOREIGN KEY ("STAFFID")
      REFERENCES "STAFF"("STAFFID")
);

CREATE TABLE "AUDITLOG" (
  "AUDITLOGID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "STAFFID" INT ,
  "DESCRIPTION" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("AUDITLOGID"),
    FOREIGN KEY ("STAFFID")
      REFERENCES "STAFF"("STAFFID")
);

CREATE TABLE "CATEGORYLIST" (
  "CATEGORYLISTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "PRODUCTCODE" INT NOT NULL,
  "CATEGORYID" INT NOT NULL,
  PRIMARY KEY ("CATEGORYLISTID"),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("CATEGORYID")
      REFERENCES "CATEGORY"("CATEGORYID")
);


/*10 Categories*/
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('CAT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('DOG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('BIRD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('FISH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('REPTILE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('SMALL ANIMAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('FOOD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('TOY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('ACCESSORY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORYNAME, CREATEDDATE, MODIFIEDDATE) VALUES ('MEDICINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

/*Customers*/
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Johnny', 'Johnny', 'Doe', 'johnny@gmail.com','johnny', '1234567890', '1234 Main St, San Jose, CA 95131', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Jane', 'Jane', 'Doe', 'jane@gmail.com','janedoe', '1235436200', '1200 Street, West Croft, CE 9211', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Ahmad', 'Ahmad', 'Ibrahim', 'ahmadibrahim@gmail.com','ahmadd', '0123456789', '24, Jalan Raja Chulan, 50200 Kuala Lumpur', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Nurul', 'Nurul', 'Azizan', 'nurulazizan@gmail.com','nurulll', '0198765432', '89, Jalan Tun Razak, 55000 Kuala Lumpur', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Siti', 'Siti', 'Abdullah', 'sitiabdullah@gmail.com','sitiii', '0176543210', '12, Jalan Bukit Bintang, 55100 Kuala Lumpur', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Wan', 'Wan', 'Ishak', 'wanishak@gmail.com','wanwannwa', '0131112222', '45, Jalan Ampang, 50450 Kuala Lumpur', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Michelle', 'Michelle', 'Tan', 'michelle@gmail.com','michelle', '0123456789', '56 Jalan Ampang, Kuala Lumpur, 50450', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('David', 'David', 'Wong', 'david@gmail.com','davidson', '0112345678', '20 Jalan Bukit Bintang, Kuala Lumpur, 55100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Siti', 'Siti', 'Ahmad', 'siti@gmail.com','sitisiuti', '0198765432', '32 Jalan Tengku Ampuan, Shah Alam, 40100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Michael', 'Michael', 'Ng', 'michael@gmail.com','michaella', '0167890123', '43 Jalan SS15/4D, Subang Jaya, 47500', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Samantha', 'Samantha', 'Lee', 'samantha@gmail.com','samanthaha', '0178901234', '77 Jalan Kuchai Maju 5, Kuala Lumpur, 58200', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Siti', 'Siti', 'Salleh', 'siti@gmail.com', 'salleh123', '0198765432', '32 Jalan Tengku Ampuan, Shah Alam, 40100', '2023-01-15 12:30:45.001', '2023-01-15 12:30:45.001');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Farhan', 'Farhan', 'Ismail', 'farhan.ismail@gmail.com', 'farhan123', '0176543210', '456 Jalan Ampang, Kuala Lumpur, 50450', '2023-03-10 10:45:00', '2023-03-10 10:45:00');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Razif', 'Razif', 'Hassan', 'razif.hassan@gmail.com', 'razif123', '0134567890', '101 Jalan Kenari, Seremban, 70200', '2023-05-08 17:10:00', '2023-05-08 17:10:00');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Nadia', 'Nadia', 'Mohd Yusof', 'nadia.yusof@gmail.com', 'nadia123', '0167890123', '555 Jalan Jelatek, Ampang, 68000', '2023-06-02 12:00:00', '2023-06-02 12:00:00');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Aisyah', 'Aisyah', 'Azman', 'aisyah.azman@gmail.com', 'aisyah123', '0112345678', '444 Jalan Kuching, Kuala Lumpur, 51200', '2023-07-18 09:15:00', '2023-07-18 09:15:00');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Amir', 'Amir', 'Ibrahim', 'amir.ibrahim@gmail.com', 'amir123', '0145678901', '123 Jalan Bukit Bintang, Kuala Lumpur, 55100', '2023-08-12 09:15:00', '2023-08-12 09:15:00');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Li Ming', 'Li', 'Ming', 'liming@gmail.com', 'liming123', '0123456789', '27 Jalan SS2/75, Petaling Jaya, Selangor, 47300', '2023-05-07 14:30:00.000', '2023-05-07 14:30:00.000');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Tan Wei Ling', 'Tan', 'Wei Ling', 'tanweiling@gmail.com', 'tweiling456', '0112345678', '56 Jalan Bukit Bintang, Kuala Lumpur, 55100', '2023-05-08 10:15:00.000', '2023-05-08 10:15:00.000');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Wong Kim Fong', 'Wong', 'Kim Fong', 'wongkimfong@gmail.com', 'wkf789456', '0198765432', '12 Jalan Besar, Melaka, 75200', '2023-05-09 08:45:00.000', '2023-05-09 08:45:00.000');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('John Lee', 'John', 'Lee', 'johnlee@gmail.com', 'jlee123', '0167890123', '21 Jalan Gasing, Petaling Jaya, Selangor, 46000', '2023-05-10 11:30:00.000', '2023-05-10 11:30:00.000');
INSERT INTO CUSTOMER (CUSTOMERNAME, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CREATEDDATE, MODIFIEDDATE) VALUES ('Lim Hui Ling', 'Lim', 'Hui Ling', 'limhuiling@gmail.com', 'lhui567', '0134567890', '45 Jalan Raja Chulan, Kuala Lumpur, 50200', '2023-05-11 15:00:00.000', '2023-05-11 15:00:00.000');


/*Cart*/
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (101, '2023-05-07 14:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (102, '2023-05-08 10:15:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (103, '2023-05-09 08:45:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (104, '2023-05-10 11:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (105, '2023-05-11 15:00:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (106, '2023-05-12 09:15:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (107, '2023-05-13 08:45:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (108, '2023-05-14 11:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (109, '2023-05-15 15:00:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (110, '2023-05-16 09:15:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (111, '2023-05-17 08:45:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (112, '2023-05-18 11:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (113, '2023-05-19 15:00:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (114, '2023-05-20 09:15:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (115, '2023-05-21 08:45:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (116, '2023-05-22 11:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (117, '2023-05-23 15:00:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (118, '2023-05-24 09:15:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (119, '2023-05-25 08:45:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (120, '2023-05-26 11:30:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (121, '2023-05-27 15:00:00.000');
INSERT INTO CART (CUSTOMERID, MODIFIEDDATE) VALUES (122, '2023-05-28 09:15:00.000');

/*2 Promotions*/
INSERT INTO PROMOTION(VALUE,DESCRIPTION,STATUS,CREATEDDATE,MODIFIEDDATE) VALUES (10,'10% off for all items','DEACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PROMOTION(VALUE,DESCRIPTION,STATUS,CREATEDDATE,MODIFIEDDATE) VALUES (20,'20% Raya Sale','DEACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*21 Products*/
/*bird*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('SAVIC CAMILLE 30','Color : Warm Grey',192.00,30, 'SAVIC.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('SMARTHEART PARROTS & CONURES','Weight : 400g',14.00,50, 'SMARTHEART.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('VERSELE-LAGA PREMIUM AFRICAN PARROTS','Weight : 1kg',43.00,50, 'PRESTIGE.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('WILD BIRD TOY WITH SWING','Color: Brown',85.00,20, 'SWING.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
/*cat*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('APPLAWS (CAT)TIN SENIOR TUNA WITH SALMON','Weight: 70g',6.00,100, 'APPLAWS.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('MERA BETTER CAT - SENIOR CHICKEN','Weight: 2kg',68.00,40, 'MERABETTER.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('GIZMO LITTER TRAY (LARGE)','Color: Mocca',55.00,20, 'GIZMOLITTER.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('SMARTYKAT MADCAP MOUSE','REFILLABLE CATNIP TOY',41.00,30, 'SMARTYKAT.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('ORIJEN 6 FISH CAT  KITTEN','Weight: 1.8kg',162.00,60, 'ORIJEN.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*dog*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('ACANA GRASS-FED LAMB','Weight: 2kg',118.00,40, 'ACANAGRASS.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('ACANA PACIFICA DOG','Weight: 2kg',115.00,30, 'ACANAPACIFICA.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('AMY N CAROL PLUSH-MR DONUT','Color: Blue',17.50,20, 'AMYNCAROLPLUSH.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('MCM CHEWY NATURAL PRESSED BONE','Width: 12inches',25.00,30, 'MCMCHEWY.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('TRUSTIE OXFORD ROUND PET','Color: Blue',78.00,50, 'TRUSTIE.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*fish*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('AQUANICE H2O BIO BALANCE SUPER BACTERIA','Weight: 250ml',30.00,100, 'AQUANICEH2O.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('AQUANICE INCH GOLD DRIED SHRIMP','Weight: 85g',50.00,100, 'AQUANICEINCH.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*reptile*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('MPS ITALIAN PET COMMA','Size: MEDIUM',30.00,20, 'MPS.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('TROPICAL GAMMARUS','Weight: 12g',1.00,50, 'TROPICAL.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*additions*/
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('SMARTHEART COCKATIEL & LOVEBIRD','Weight: 1kg',15.00,20, 'LOVEBIRD.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(PRODUCTNAME,DESCRIPTION,PRICE,STOCK,IMAGE,PROMOTIONID,CREATEDDATE,MODIFIEDDATE) VALUES ('BEEZTEES WOODEN BIRD TOY FLOX','Color: Red',26.00,20, 'BEEZTEESBIRD.jpg', null ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*10 staff*/
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('admin','adminpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('staff','staffpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('nicholas','special',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('jason','jasonpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('james','jamespass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('joshua','joshuapass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('joseph','josephpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('jacob','jacobpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('jackson','jacksonpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO STAFF(STAFFNAME,PASSWORD,CREATEDDATE,MODIFIEDDATE) VALUES ('julian','julianpass',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

/*10 payment*/
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567890','Card',200,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567891','Card',95,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567892','Card',300,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567893','Cash',400,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567894','Card',500,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567895','Cash',600,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567896','Cash',700,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567897','Card',800,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567898','Card',900,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('1234567899','Cash',1000,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('98765432100','Cash',500,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('19283746598','Card',200,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('56473829103','Cash',700,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('28193047464','Card',800,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('38475629102','Cash',1000,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('10293847566','Card',1500,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('29384756699','Cash',900,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('47583920123','Card',300,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('39485761230','Cash',1200,CURRENT_TIMESTAMP);
INSERT INTO PAYMENT(TRANSACTIONID,METHOD,TOTAL,CREATEDDATE) VALUES ('82736495839','Card',600,CURRENT_TIMESTAMP);


/*10 orders*/
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (101,8,10,100,115,'0123456789','1, Jalan 1, Taman 1, 11111, Kuala Lumpur','Packing',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (102,1,0,200,200,'0123456789','2, Jalan 2, Taman 2, 22222, Kuala Lumpur','Shipping',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (103,2,30,100,95,'0123456789','3, Jalan 3, Taman 3, 33333, Kuala Lumpur','Shipping',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (104,3,0,400,400,'0123456789','4, Jalan 4, Taman 4, 44444, Kuala Lumpur','Delivered',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (105,4,50,500,450,'0123456789','5, Jalan 5, Taman 5, 55555, Kuala Lumpur','Packing',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (106,5,0,600,600,'0123456789','6, Jalan 6, Taman 6, 66666, Kuala Lumpur','Delivered',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (107,6,0,700,700,'0123456789','7, Jalan 7, Taman 7, 77777, Kuala Lumpur','Shipping',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (108,7,0,800,800,'0123456789','8, Jalan 8, Taman 8, 88888, Kuala Lumpur','Shipping',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (109,9,0,900,900,'0123456789','9, Jalan 9, Taman 9, 99999, Kuala Lumpur','Packing',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (110,10,0,1000,1000,'0123456789','10, Jalan 10, Taman 10, 101010, Kuala Lumpur','Packing',CURRENT_TIMESTAMP);
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (101,11,10,100,115,'0123456789','1, Jalan 1, Taman 1, 11111, Kuala Lumpur','Shipping','2022-09-01 09:10:23');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (102,12,20,200,210,'0123456789','2, Jalan 2, Taman 2, 22222, Kuala Lumpur','Delivered','2022-11-15 15:30:45');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (103,13,0,150,150,'0123456789','3, Jalan 3, Taman 3, 33333, Kuala Lumpur','Packing','2022-12-31 23:59:59');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (104,14,30,250,270,'0123456789','4, Jalan 4, Taman 4, 44444, Kuala Lumpur','Shipping','2022-10-10 10:10:10');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (105,15,0,50,50,'0123456789','5, Jalan 5, Taman 5, 55555, Kuala Lumpur','Delivered','2022-11-11 11:11:11');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (121,16,0,400,400,'0123456789','1, Jalan 21, Taman 21, 21212, Kuala Lumpur','Delivered','2023-06-07 17:20:00');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (118,17,25,250,225,'0123456789','1, Jalan 18, Taman 18, 18181, Kuala Lumpur','Shipping','2023-05-01 09:15:00');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (113,18,0,700,700,'0123456789','1, Jalan 13, Taman 13, 13131, Kuala Lumpur','Packing','2023-04-10 10:00:00');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (109,19,50,500,450,'0123456789','1, Jalan 9, Taman 9, 99999, Kuala Lumpur','Delivered','2023-03-05 15:45:00');
INSERT INTO ORDERS(CUSTOMERID,PAYMENTID,PROMOTIONVALUE,SUBTOTAL,TOTAL,PHONENUMBER,ADDRESS,STATUS,CREATEDDATE) VALUES (107,20,0,300,300,'0123456789','1, Jalan 5, Taman 5, 55555, Kuala Lumpur','Shipping','2023-02-18 13:30:00');

/*20 orderlist*/
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (101,2001,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (102,2002,2);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (103,2003,3);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (104,2004,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (105,2005,2);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (106,2006,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (107,2007,3);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (108,2008,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (109,2009,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (110,2010,5);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (101,2011,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (102,2012,2);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (103,2013,3);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (104,2014,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (105,2001,2);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (106,2002,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (107,2003,3);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (108,2004,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (109,2005,1);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES (110,2006,5);
INSERT INTO ORDERLIST(ORDERID,PRODUCTCODE,QUANTITY) VALUES 
(101, 2004, 3),
(101, 2010, 2),
(101, 2020, 1),
(102, 2001, 1),
(102, 2003, 4),
(102, 2016, 2),
(103, 2008, 3),
(103, 2012, 1),
(103, 2015, 2),
(104, 2002, 2),
(104, 2005, 1),
(104, 2007, 3),
(105, 2009, 4),
(105, 2011, 1),
(105, 2020, 2),
(106, 2006, 3),
(106, 2013, 1),
(106, 2017, 2),
(107, 2001, 1),
(107, 2003, 2),
(107, 2018, 4),
(108, 2008, 2),
(108, 2012, 3),
(108, 2016, 1),
(109, 2002, 1),
(109, 2011, 3),
(109, 2020, 2),
(110, 2004, 2),
(110, 2007, 1),
(110, 2019, 4),
(111,2004,2),
(111,2005,1),
(112,2001,4),
(112,2003,2),
(113,2002,3),
(113,2004,1),
(114,2005,2),
(114,2002,1),
(115,2007,3),
(115,2012,2),
(116,2001,1),
(116,2003,2),
(117,2004,4),
(117,2018,1),
(118,2016,1),
(118,2019,3),
(119,2009,2),
(119,2011,1),
(120,2005,3),
(120,2010,1);

/*CATEGORYLIST*/
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2005,1);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2006,1);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2007,1);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2008,1);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2009,1);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2010,2);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2011,2);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2012,2);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2013,2);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2014,2);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2001,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2002,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2003,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2004,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2015,4);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2016,4);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2017,5);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2018,5);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2001,9);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2002,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2003,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2004,9);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2005,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2006,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2007,9);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2008,8);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2009,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2010,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2011,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2012,8);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2013,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2014,9);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2015,10);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2016,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2017,9);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2018,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2019,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2019,7);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2020,3);
INSERT INTO CATEGORYLIST(PRODUCTCODE,CATEGORYID) VALUES (2020,9);

INSERT INTO AUDITLOG(STAFFID, DESCRIPTION, CREATEDDATE) VALUES(201, 'Updated order, order id : 101', CURRENT_TIMESTAMP);