CREATE TABLE "CATEGORY" (
  "CATEGORYID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CATEGORYNAME" VARCHAR(20) NOT NULL,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CATEGORYID")
);

CREATE TABLE "CUSTOMER" (
  "CUSTOMERID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 101, INCREMENT BY 1),
  "CUSTOMERNAME" VARCHAR(30),
  "FIRSTNAME" VARCHAR(20),
  "LASTNAME" VARCHAR(30),
  "EMAIL" VARCHAR(50) NOT NULL,
  "PASSWORD" VARCHAR(70) NOT NULL,
  "PHONENUMBER" VARCHAR(20),
  "ADDRESS" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CUSTOMERID")
);

CREATE TABLE "ORDERS" (
  "ORDERID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 101, INCREMENT BY 1),
  "CUSTOMERID" INT NOT NULL,
  "PAYMENTID" INT NOT NULL,
  "PROMOTIONVALUE" DOUBLE,
  "SUBTOTAL" DOUBLE,
  "TOTAL" DOUBLE,
  "PHONENUMBER" VARCHAR(20),
  "ADDRESS" LONG VARCHAR,
  "STATUS" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ORDERID"),
    FOREIGN KEY ("CUSTOMERID")
      REFERENCES "CUSTOMER"("CUSTOMERID")
);

CREATE TABLE "PROMOTION" (
  "PROMOTIONID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "VALUE" INTEGER,
  "DESCRIPTION" LONG VARCHAR,
  "STATUS" VARCHAR(10),
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PROMOTIONID")
);

CREATE TABLE "PRODUCT" (
  "PRODUCTCODE" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 2001, INCREMENT BY 1),
  "PRODUCTNAME" VARCHAR(40),
  "DESCRIPTION" LONG VARCHAR,
  "PRICE" DOUBLE,
  "STOCK" INTEGER,
  "IMAGE" LONG VARCHAR,
  "PROMOTIONID" INT,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PRODUCTCODE"),
    FOREIGN KEY ("PROMOTIONID")
      REFERENCES "PROMOTION"("PROMOTIONID")
);

CREATE TABLE "ORDERLIST" (
  "ORDERLIST" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 201, INCREMENT BY 1), 
  "ORDERID" INT NOT NULL,
  "PRODUCTCODE" INT NOT NULL,
  "QUANTITY" INTEGER,
  PRIMARY KEY (ORDERLIST),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("ORDERID")
      REFERENCES "ORDERS"("ORDERID")
);

CREATE TABLE "STAFF" (
  "STAFFID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 201, INCREMENT BY 1),
  "STAFFNAME" VARCHAR(30),
  "PASSWORD" VARCHAR(70) NOT NULL,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("STAFFID")
);

CREATE TABLE "PAYMENT" (
  "PAYMENTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "TRANSACTIONID" VARCHAR(15),
  "METHOD" VARCHAR(25),
  "TOTAL" DOUBLE,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PAYMENTID")
);

CREATE TABLE "CART" (
  "CARTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CUSTOMERID" INT NOT NULL,
  "MODIFIEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CARTID")
);

CREATE TABLE "CARTLIST" (
  "CARTLISTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "CARTID" INT NOT NULL,
  "PRODUCTCODE" INT NOT NULL,
  "QUANTITY" INTEGER,
  PRIMARY KEY ("CARTLISTID"),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("CARTID")
      REFERENCES "CART"("CARTID")
);

CREATE TABLE "REFUND" (
  "REFUNDID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "PAYMENTID" INT NOT NULL,
  "STAFFID" INT NOT NULL,
  "STATUS" VARCHAR(10),
  "REASON" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("REFUNDID"),
    FOREIGN KEY ("STAFFID")
      REFERENCES "STAFF"("STAFFID")
);

CREATE TABLE "AUDITLOG" (
  "AUDITLOGID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "STAFFID" INT ,
  "DESCRIPTION" LONG VARCHAR,
  "CREATEDDATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("AUDITLOGID"),
    FOREIGN KEY ("STAFFID")
      REFERENCES "STAFF"("STAFFID")
);

CREATE TABLE "CATEGORYLIST" (
  "CATEGORYLISTID" INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "PRODUCTCODE" INT NOT NULL,
  "CATEGORYID" INT NOT NULL,
  PRIMARY KEY ("CATEGORYLISTID"),
    FOREIGN KEY ("PRODUCTCODE")
      REFERENCES "PRODUCT"("PRODUCTCODE"),
    FOREIGN KEY ("CATEGORYID")
      REFERENCES "CATEGORY"("CATEGORYID")
);
